In [8]:
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
tf.one_hot([1], depth=6)

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
l = ['a', 'b', 'c']

In [19]:
x = np.array(l)

In [29]:
tf.constant([float(i) for i in x == 'a'])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 0., 0.], dtype=float32)>

In [ ]:
label_dict = 

In [1]:
# reshaping to 3 channels

In [96]:
import numpy as np

In [113]:
img = [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1],  [1, 1, 1, 1]]

In [114]:
v = np.array(img)

In [115]:
v.shape

(4, 4)

In [116]:
v = np.reshape(v, (4, 4, 1))

In [117]:
v = np.append(v, v, axis=2)


In [118]:
v.shape

(4, 4, 2)

In [119]:
v = np.append(v, np.reshape(np.array(img), (4, 4, 1)), axis=2)

In [120]:
v

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [121]:

v.shape

(4, 4, 3)